### ISSUE TITLE
About visualization, matplotlib visualization failed

### ISSUE THREAD

**Issue by Ancolie18** [Garfield-kh/TM2D#14]
Thank you for your excellent open source work! When I tried to reproduce the work, I encountered some problems:

1、When I run two evaluation codes, I output two types of files, including SMPL data for motion and a visual mp4 file. But the mp4 file only has a title and does not seen the skeleton. I am unable to identify the cause, may I ask if there is any possible mistake?
![image](https://github.com/user-attachments/assets/43216607-b56b-4d7a-abda-5930b4c9275c)

2、In addition, when I used other methods such as Unity to directly visualize SMPL data, I found that the generated actions were not normal dance movements, even the npy motion file in dataset (aistppml3d\new_joints\000000.npy). How to visualize npy data? Do you have a reference code?
![image](https://github.com/user-attachments/assets/7367e67f-9282-4320-bf11-aa1364b9a60c)

May I ask if there are any other visual methods to verify the effectiveness of actions? thank you! We look forward to your reply

**Comment by Garfield-kh** [comment]
`1、When I run two evaluation codes, I output two types of files, including SMPL data for motion and a visual mp4 file. But the mp4 file only has a title and does not seen the skeleton. I am unable to identify the cause, may I ask if there is any possible mistake?`
is that due to the unit mm (x1000) or m? can you try plot it frame by frame in matplotlib?

`2、In addition, when I used other methods such as Unity to directly visualize SMPL data, I found that the generated actions were not normal dance movements, even the npy motion file in dataset (aistppml3d\new_joints\000000.npy). How to visualize npy data? Do you have a reference code?`
This is caused by the mismatch of Skeleton Rigging, you need to have the corresponding Rigging in unity.

**Comment by JiyeongCha** [comment]
How did you solve problem 1?
